architecture:
  d_in: 2
  student:
    activation_function: g
    bias_1: true
    bias_2: true
    hidden_layers: 2
    number_neurons_1: 12
    number_neurons_2: 12
  teacher:
    activation_function: g
    bias_1: true
    bias_2: true
    hidden_layers: 2
    number_neurons_1: 3
    number_neurons_2: 3
data_gen:
  data_plan: file
  data_specification: sample
  teacher_specification: sample
experiment:
  iterations_per_dataset: 7
  name: '0000'
  name_prefix: '20240603'
  number_datasets: 1
  number_of_teachers: 1
  parallelism: none
  processors: 1
train_params:
  maxiterations_ode: 10000000000.0
  maxiterations_optim: 10000000.0
  maxtime_ode: 3600
  maxtime_optim: 3600
  verbosity: 1
